#Base
FROM ubuntu
ENV DEBIAN_FRONTEND noninteractive
WORKDIR /home/pifordecoyer/code/cpp/GenshinCard
COPY dependencies .
RUN apt-get update -y && \
    apt-get install -y python3.10 python3-pip git-all build-essential pkg-config `cat dependencies`
WORKDIR /app/ImageMagick
RUN git clone https://github.com/ImageMagick/ImageMagick.git /app/ImageMagick && \
    ./configure CXX=g++ && \
#    --prefix=/app/GenshinCard/ImageMagick \
#    CPPFLAGS=-I/app/GenshinCard/ImageMagick/include \
#    LDFLAGS=-L/app/GenshinCard/ImageMagick/lib && \
    make && \
    make install
#    ldconfig /app/GenshinCard/ImageMagick/lib
RUN git clone https://github.com/libcpr/cpr.git /app/cpr
WORKDIR /app/cpr/build
RUN cmake /app/cpr -DCPR_BUILD_TESTS=OFF && \
    make install
    
